version: '3.8'

services:
  iot-vision:
    build: .
    container_name: iot-vision-service
    ports:
      - "8000:8000"
    volumes:
      # Mount logs directory for persistent logging
      - ./logs:/app/logs
      # Mount a directory for test videos (optional)
      - ./test_videos:/app/test_videos:ro
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Optional: Add a reverse proxy (uncomment if needed)
  # nginx:
  #   image: nginx:alpine
  #   container_name: iot-vision-proxy
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - iot-vision
  #   restart: unless-stopped
